using UnitGPT.Helpers;

namespace UnitGPT.Services.OpenAI.Services
{
    internal class CSharpCodeParseResponseService : ResponseBaseService
    {
        public CSharpCodeParseResponseService(string startComment, string endComment) 
            : base(startComment, endComment, "AutoGenerated", TextHelpers.ExtractMethodName)
        {
        }
    }
}
