using UnitGPT.Helpers;
using UnitGPT.Services.OpenAI.Models;

namespace UnitGPT.Services.OpenAI.Services
{
    internal class ParseResponseService
    {
        internal static UnitTestResponseModel ParseCodeSectionFromResponseBody(string input)
        {
            var testCodeSnippet = TextHelpers.ExtractCode(input);
            testCodeSnippet = TextHelpers.CleanTextFromWord(testCodeSnippet, "csharp");
            var className = TextHelpers.ExtractClassName(testCodeSnippet);
            return new UnitTestResponseModel()
            {
                ClassName = SetDefaultClassNameIfEmpty(className),
                TestCode = testCodeSnippet
            };
        }

        private static string SetDefaultClassNameIfEmpty(string className)
        {
            if (string.IsNullOrEmpty(className))
            {
                className = $"AutoGenerated_Test_{DateTime.Now}"
                    .Replace(' ','_')
                    .Replace(':','_');
            }
            return className ;
        }
    }
}
