using UnitGPT.Helpers;
using UnitGPT.Services.OpenAI.Interface;
using UnitGPT.Services.OpenAI.Models;

namespace UnitGPT.Services.OpenAI.Services
{
    internal class UnitTestParseResponseService : ResponseBaseService
    {
        public UnitTestParseResponseService(string startComment, string endComment)
            : base( startComment, endComment, "AutoGenerated_Test", TextHelpers.ExtractClassName)
        {
        }
    }
}
