// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnitGPT
{
    internal sealed partial class Vsix
    {
        public const string Id = "UnitGPT.04a9da1c-1aa5-4de7-8ebc-c3ae22643253";
        public const string Name = "UnitGPT";
        public const string Description = @"Extension for generating unit-tests and C# code with OpenAi. ";
        public const string Language = "en-US";
        public const string Version = "1.2.2";
        public const string Author = "UpNorthBytes";
        public const string Tags = "unittest, openai, xunit, codegeneration, comments";
    }
}
