// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnitGPT
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string UnitGPTString = "0e628c5d-9de4-412a-b449-b73d62ca694f";
        public static Guid UnitGPT = new Guid(UnitGPTString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int GenerateTestCommand = 0x0100;
        public const int GenerateCodeCommand = 0x0200;
    }
}